### ISSUE TITLE
Přidat .gitignore

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/zobrazeni-dat-nkod-dle-ofn#1]
Po `npm i` je vytvořen adresář `node_modules` který není v `.gitignore` a tedy se bere jako změna v repo, což není dobře.

**Comment by strakajakub** [comment]
přidáno zde https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/commit/135a59f4b0a6cf3fd3d5b4440d06677617405503
