### ISSUE TITLE
Použití console.log

### ISSUE THREAD

**Issue by skodapetr** [opendata-mvcr/zobrazeni-dat-nkod-dle-ofn#10]
Na https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/blob/main/src/common.ts#L52 je disable varování na ```console.log```  další jsou pak zakomentované (65, 75). Čekal bych, že buď je cílem je opravdu nepoužívat pak tam nebudou vůbec. Nebo pokud je jejich použití záměrem, proti čemuž nic nemám, tak upravit pravidlo v linteru aby to ignoroval a ty zakomentované použití odkomentovat.

**Comment by strakajakub** [comment]
opraveno [zde](https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/commit/e93e5ff4705609de34c0bb8f499bdfee3966d1d9)
