### ISSUE TITLE
Použití async keyword

### ISSUE THREAD

**Issue by skodapetr** [opendata-mvcr/zobrazeni-dat-nkod-dle-ofn#11]
Třeba na https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/blob/main/src/common.ts#L48 funkce vrací promise. Nemohla by tato funkce, a jí podobné, být označená jako async ?

**Comment by strakajakub** [comment]
[upraveno](https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/commit/718de084fb9f36069b1242ef86d33dc6907f0f10)
Dobrý postřeh, faktický rozdíl jsem doteď neznal, tak jsem to dostudoval.
