### ISSUE TITLE
If-else podmínky

### ISSUE THREAD

**Issue by skodapetr** [opendata-mvcr/zobrazeni-dat-nkod-dle-ofn#12]
Občas bývá používanou praxí vždy používat závorky po if statementu. 
Tedy podmínka na https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/blob/main/src/common.ts#L57 by vypadala 
```
if (userRenderValueFn) { 
  renderValueFn = userRenderValueFn;
}
```
alternativou, možná vhodnou v tomto případě, je použití terciálního zápisu. 
```
const renderValueFn  = userRenderValueFn ? userRenderValueFn : (row, key) => row[key].value ;
```
případně bych se nebál tu funkcio vytáhnout mimo a pojmenovat, tak jak říká komentář, jako nějaký default render.

**Comment by strakajakub** [comment]
Opraveno, přidáno pravidlo do ESLintu https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/commit/5932cd477d9a8437194b5b80538ad0156015a3cc
