### ISSUE TITLE
Připravit si složité argumenty do proměné

### ISSUE THREAD

**Issue by skodapetr** [opendata-mvcr/zobrazeni-dat-nkod-dle-ofn#13]
Třeba na https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/blob/303c3e01968f62247dcfead68952aee5309324db/src/common.ts#L98
by IMHO z hlediska čitelnosti pomohlo, když by se ten první argument připravil do const proměné a pak se zavolala funkce. 

Neb takhle skoro zapomenu, že se volá funkce než dočtu výpočet prvního argumentu. Současně je použití druhého tak trochu schované.

**Comment by strakajakub** [comment]
https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/commit/9102f246b7c4f362af977c8446034a1248b8e316
