### ISSUE TITLE
Zvážit konzistentní pojmenování pro render funkce

### ISSUE THREAD

**Issue by skodapetr** [opendata-mvcr/zobrazeni-dat-nkod-dle-ofn#14]
Na https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/blob/303c3e01968f62247dcfead68952aee5309324db/src/common.ts#L97 je funkce ```formatAppURL```, která zformátuje parametry do URL, ta ale ve skutečnosti nevrací zformátované URL ale kód pro HTML link. 

Možná by pomohlo nějak konzistateně nazývat funkce, jenž vlastně generují html. Třeba linkAsHtml, ... 
současně pokud se nějaký argument předává ve více funkcích (konfigurace aplikace), ho dával vždy na stejné (první) místo.

**Comment by strakajakub** [comment]
Vyřešeno [zde](https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/commit/fc4522b72b330684082cf536a289dbb71d01970a)
