### ISSUE TITLE
Rozdíl mezi Config  a AppConfig 

### ISSUE THREAD

**Issue by skodapetr** [opendata-mvcr/zobrazeni-dat-nkod-dle-ofn#15]
Definované v https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/blob/303c3e01968f62247dcfead68952aee5309324db/src/common.ts  .. možná by šlo zvolit nějaké lepší pojmenování. Neb tohle pak vede k funkcím jako https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/blob/303c3e01968f62247dcfead68952aee5309324db/src/common.ts#L115 kde není úplně jasné co se vlastně děje a jaký je rozdíl mezi těmi konfiguracemi.

**Comment by strakajakub** [comment]
Upraveno [zde](https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/commit/8531a4fbcf5635fb7a779891332ddd33613a599a)
