### ISSUE TITLE
URL parametr by neměl obsahovat < > u IRI

### ISSUE THREAD

**Issue by strakajakub** [opendata-mvcr/zobrazeni-dat-nkod-dle-ofn#18]
* při přídání parametru do URL by nemělo být potžeba psát < a >, změnit, aby to umělo obě verze
EDIT: pouze bez <> verze bude podporována

**Comment by jakubklimek** [comment]
Spíše by to mělo být jen správně

**Comment by strakajakub** [comment]
Opraveno https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/commit/995a23bb3d6fb266d076954aab25de60de75b68c
