### ISSUE TITLE
Chybné generování URL pro externí aplikace

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/zobrazeni-dat-nkod-dle-ofn#19]
URL pro externí aplikace se generuje chybně.
Pro tuto konfiguraci:
```json
"url": "https://opendata-mvcr.github.io/app-ofn-plakaty/#/",
"formát_url": "dataurl=${0}"
```
URL souboru: https://oha03.mvcr.gov.cz/soubory/více-cílů.jsonld

bych čekal URL:
`https://opendata-mvcr.github.io/app-ofn-plakaty/#/?dataurl=https://oha03.mvcr.gov.cz/soubory/více-cílů.jsonld`.
Nicméně dostanu:
`https://opendata-mvcr.github.io/app-ofn-plakaty/#//?dataurl%3Dhttps%3A%2F%2Foha03.mvcr.gov.cz%2Fsoubory%2Fvíce-cílů.jsonld`
kde je celá řada problémů.
1. lomítko navíc
2. encodované `=`
3. encodovaná lomítka (možná nevadí)

**Comment by strakajakub** [comment]
Opraveno https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/commit/f31372e241b9690b62739ee5cf62bf468289faa4
