### ISSUE TITLE
Prohlížení konkrétních dat nefunguje

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/zobrazeni-dat-nkod-dle-ofn#20]
Data aplikace dostane, ale nezobrazí:
![image](https://user-images.githubusercontent.com/718827/104692417-3d9d3580-5708-11eb-843c-3451e67c1b3c.png)

Možná to souvisí s chybou v konzoli?
![image](https://user-images.githubusercontent.com/718827/104692925-0c713500-5709-11eb-9962-fc9a285be16a.png)

**Comment by strakajakub** [comment]
To je problém s lokální proxy, asi už je načase nahradit nějakou službou na heroku, nebo v AWS.

**Comment by jakubklimek** [comment]
Nevidím důvod, proč by se ale nemělo načít nic. Je tam "vícecílový" soubor, který je vystaven správně s CORS - tedy ten by se zpracovat měl i bez proxy.

**Comment by strakajakub** [comment]
https://nordicapis.com/10-free-to-use-cors-proxies/

**Comment by strakajakub** [comment]
Opraveno zde: https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/commit/3c7d4a9633950b19e115a173db6c54fae199bb21
Jede to s proxy (vice cilu), nebo bez procy (mene cilu, reportuje chyby v konzoli), dalsi reseni pres proxy bych resil v jinem issue
