### ISSUE TITLE
Rozlišení aplikací, které pracují s datovou sadou a s konkrétním objektem

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/zobrazeni-dat-nkod-dle-ofn#21]
V konfiguraci aplikací mohou aplikace brát 2 parametry - URL celého souboru, a volitelně IRI konkrétní entity (turistického cíle) viz https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/blob/f23a649f505f34b47627dc74996459e021bdfaef/src/conf/applications.json#L7 a https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/blob/f23a649f505f34b47627dc74996459e021bdfaef/src/conf/applications.json#L14

Nedává pak ale smysl, aby se aplikace nakonfigurovaná pro zpracování konrétní entity s IRI zobrazovala v prohlížení datových sad jako celku:
![image](https://user-images.githubusercontent.com/718827/104692736-c0be8b80-5708-11eb-953e-7c78d853be2b.png)
![image](https://user-images.githubusercontent.com/718827/104692798-dc299680-5708-11eb-87df-f617b7f27065.png)

Jelikož tento výpis nerozlišuje jednotlivé entity (turistické cíle).

**Comment by strakajakub** [comment]
Browser má zobrazovat data, jak jsou, Demo jít na detaily a nezobrazovat "vícecílové" soubory jako položky, když uživatel chce vidět konkrétní cíle.

**Comment by strakajakub** [comment]
Opraveno zde https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/commit/3c7d4a9633950b19e115a173db6c54fae199bb21

Mozne rozsireni je, aby si puvodni dotaz v aplikaci browser pridat iri objektu do resultsetu a tento iri se vykresloval i do odkazu jako ${3}, podobne jako v aplikaci "demo" (staci napsat, jestli to chapu dobre, pripadne provedu)

**Comment by jakubklimek** [comment]
Není třeba, takhle je to OK, ale ta issue původně vedla na něco jiného.
V aplikaci browser by se zobrazovaly jen ty aplikace, které v nastavení mají pouze ${1} a v aplikaci demo jen ty aplikace, které mají v nastavení aktuálně ${1} a ${3}. Ty jiné kombinace moc nedávají smysl.
