### ISSUE TITLE
Konfigurace plakátovací aplikace

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/zobrazeni-dat-nkod-dle-ofn#4]
Plakátovací aplikace pro turistické cíle běží např. na IRI `https://opendata-mvcr.github.io/app-ofn-plakaty/#/?dataurl=https%3A%2F%2Fmichalskop.gitlab.io%2Fofnapp%2Fdata%2Fkonvent.json&iri=https%3A%2F%2Fwww.klaster-plasy.cz%2F` - mělo by být možné ji registrovat do konfigurace.

**Comment by strakajakub** [comment]
Už to funguje.
