### ISSUE TITLE
Sjednotit cesty pro import css/js

### ISSUE THREAD

**Issue by skodapetr** [opendata-mvcr/zobrazeni-dat-nkod-dle-ofn#5]
```browser.html``` obsahuje 
```
<script type="module" src="dist/bundle.js"></script>
```
HTML pro index.html pak odkazy v podobě.
```
<li><a href="/browser.html">Prohlížeč dat v OFN - browser</a></li>
```
Ten poslední typ vlastně říká, že to musí běžet přímo na doméně, zatímco ty předchozí umožňují nějaké zanožení. 
Je pro to nějaký důvod? Bylo by možné upravit odkazy začínající "/" tak aby začínali na něco jiného?

**Comment by strakajakub** [comment]
Oparveno zde https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/commit/23e67b1b93058b7bd24e1d93cccb49cab3e8fb28
