### ISSUE TITLE
Npm I vs CI

### ISSUE THREAD

**Issue by skodapetr** [opendata-mvcr/zobrazeni-dat-nkod-dle-ofn#6]
Zvážil bych do návodu použít ```npm ci```, výhoda je, že se instalují přesně knihovny podle package-lock a tedy uživatel dostane stejnou verzi jako developer.  Zároveň tím nedojde k update package-lock souboru.

**Comment by strakajakub** [comment]
Super nápad, neznal jsem, upraveno https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/commit/03980babf3748917ad3cd54ce007dc4ae0b22435
