### ISSUE TITLE
Konzistentní code style

### ISSUE THREAD

**Issue by skodapetr** [opendata-mvcr/zobrazeni-dat-nkod-dle-ofn#8]
Na 
https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/blob/main/src/common.ts#L7
https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/blob/main/src/common.ts#L31 
se občas používá zápisu klíčů v objektu bez uvozovek a občas s . Byl bych pro to aby to bylo konzistentní, další možnost je opužít nějaký linter, jenž to pohlídá.

**Comment by skodapetr** [comment]
Další je pak použití různých uvozovek například:
https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/blob/303c3e01968f62247dcfead68952aee5309324db/src/common.ts#L53
a 
https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/blob/303c3e01968f62247dcfead68952aee5309324db/src/common.ts#L74

**Comment by strakajakub** [comment]
Opraveno v https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/commit/b3f11ddc6118d45b74ec7ad2cb9e4a44797ab11d a https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/commit/77b8d7aa33734a9fe4a46103ea1a589a7a2b3398
