### ISSUE TITLE
TSLint update

### ISSUE THREAD

**Issue by skodapetr** [opendata-mvcr/zobrazeni-dat-nkod-dle-ofn#9]
Dle https://palantir.github.io/tslint/ 
> :warning: TSLint has been deprecated as of 2019. Please see this issue for more details: Roadmap: TSLint → ESLint. typescript-eslint is now your best option for linting TypeScript.

eslint by navíc mohl snadno pomoci i s #8

**Comment by strakajakub** [comment]
Změněno na ESLint a opraveny chyby, které ESLint našel, [zde](https://github.com/opendata-mvcr/zobrazeni-dat-nkod-dle-ofn/commit/bfac854222b580f2cc9fcf0e89d02fa4b95e4e64)
